Issue10 rss form
albertoag128/RssAndroidApp pull request #13
Opened 2022-11-21 19:24 UTC by albertoag128

## DESCRIPCION
Esta pull request documenta el proceso de crear un bottomsheet (una ventana modal con un formulario) para que el usuario pueda introducir los datos de sus RSS favoritas y estos se queden guardados.

## COMO HA SIDO IMPLEMENTADO
El proceso ha comenzado por crear un bottomsheet y diseñarlo. Tambien hemos implementado un view model y un factory para poder acceder el caso de uso de guardar RSS y así poder implementarlo en la vista mediante un setOnClickListener. Por último utilizando la actividad unica para el bottom sheet, añadimos un snackbar al proceso de guardado de la información del formulario para así poder confirmar al usuario que el registro ha sido guardado.

## PALABRAS CLAVE
Save, Snackbar, ViewModel, View, Fragment, Dialog, BottomSheet, Themes

## SCREENSHOTS Y VIDEOS

https://user-images.githubusercontent.com/91797204/203141213-40718630-7b75-4190-b91e-5ad28d5b6e33.mp4

![xmlprueba](https://user-images.githubusercontent.com/91797204/203141297-375cf4ee-c4ca-42c8-9a58-b3fd0ade0c00.PNG)

2022-11-22 10:53 UTC, dherranz1 approved these changes
Tiene buenta pinta :+1:

2022-11-22 14:22 UTC, josem-perram commented on app/src/main/java/com/example/rssapp/management/presentation/AddRssBottomSheetFragment.kt
> +class AddRssBottomSheetFragment : BottomSheetDialogFragment() {
Sólo los casos de uso deberían comenzar por un verbo, una acción. Aquí mejor usar un nombre, por ejemplo: FormRSSFragment. Se trata de decir lo que es la vista, un formulario, y evitar hacer referencia a lo que hace.

2022-11-22 14:24 UTC, josem-perram commented on app/src/main/java/com/example/rssapp/management/presentation/AddRssBottomSheetFragment.kt
> +    fun setSaveButton() {
Sugerencia: setupSaveButton. Lo que haces aquí es configurarlo: añadir un listener... si tuvieras más configuraciones el namings sería más tipo: setupView. El setSaveButton se suena más a como que estableces el botón save, algo más a:
this.saveButton = findView.... lo que sea. Como cuando hacemos los getters y setters de java.

2022-11-22 14:25 UTC, josem-perram commented on app/src/main/java/com/example/rssapp/management/presentation/AddRssBottomSheetFragment.kt
> +    fun showSnackbar() {
este naming es perfecto, describe lo que hace.

2022-11-22 14:26 UTC, josem-perram commented on app/src/main/java/com/example/rssapp/management/presentation/AddRssBottomSheetFragment.kt
> +    fun setCancelButton() {
diría lo mismo aquí, en este código estás añadiendo una configuración al botón que es establecer un listener. Como propuesta, yo haría un setupView donde metería todas estas configuraciones de setOnClickListener.

2022-11-22 14:26 UTC, josem-perram commented on app/src/main/java/com/example/rssapp/management/presentation/RssManagerFragment.kt
> +    override fun onResume() {
Esto lo puedes eliminar.

2022-11-23 11:43 UTC, dherranz1 approved these changes
:+1:

2022-11-25 17:14 UTC, jmperezra requested changes
@albertoag128 La línea a seguir con respecto a la documentación ese esta, muy bien documentada. Te he dejado unos comentarios que quiero que revises. @dherranz1 please, revísalos tu tb. Gracias.

2022-11-25 17:14 UTC, jmperezra commented on app/src/main/java/com/example/rssapp/management/presentation/RssBottomSheetFragment.kt
> +                dismiss()
@albertoag128 prueba a cambiar el dismiss por el  findNavController().navigateUp(), esto es para quitar el dialogo de la pila. Con Dismiss simplemente lo cerramos.

2022-11-25 17:14 UTC, jmperezra commented on app/src/main/java/com/example/rssapp/management/presentation/RssBottomSheetFragment.kt
> +                findNavController().navigate(R.id.action_from_bottomSheet_to_rssManager)
Lo mismo aquí:  findNavController().navigateUp()

2022-11-25 17:14 UTC, jmperezra commented on app/src/main/java/com/example/rssapp/management/presentation/RssBottomSheetFragment.kt
> +            "Registro guardado",
Acuérdate internacionalizar: strings.xml
@dherranz1 cuidado con esto, que se ha corregido la PR y aquí hay cosas que mejorar.

2022-11-25 17:14 UTC, jmperezra commented on app/src/main/java/com/example/rssapp/management/presentation/RssManagerFragment.kt
> +    fun openBottomSheet(){
Quizás este naming es erróneo. Cuando lo he visto, lo primero que he pensado es que este método abría el bottomSheet. Como hemo hablado otras veces, yo haría un setupView() y metería todo lo que tiene que ver con añadir eventos (ClickListener, etc.), strings, etc.

2022-11-25 17:14 UTC, jmperezra commented on app/src/main/java/com/example/rssapp/management/presentation/RssManagerFragment.kt
> +        findNavController().navigate(R.id.action_from_rssManager_to_bottomSheet)
acuérdate de usar safeargs.

2022-11-25 17:14 UTC, jmperezra commented on app/src/main/java/com/example/rssapp/management/presentation/RssManagerViewModel.kt
> +        val isSuccess: Boolean = false
Teniendo ya el caso de uso, yo metería ya el modelo que devuelve el caso de uso en el modelo UiState.

2022-11-25 17:14 UTC, jmperezra commented on app/src/main/res/layout/add_new_rss_bottom_sheet.xml
> +        android:hint="Nombre de la rss"
strings.xml

2022-11-28 19:19 UTC, albertoag128 commented
Hola, tuve un problema con las versiones del proyecto, pero en principio estaría todo implementado y los cambios realizados.

2022-12-22 14:41 UTC, josem-perram approved these changes
ok, genial.

2022-12-22 14:41 UTC, josem-perram commented on app/src/main/java/com/example/rssapp/management/presentation/RssBottomSheetFragment.kt
> +                viewModel?.saveRss(
@albertoag128 esto es lo que hablamos del error del save. Te doy aquí el ok debido a las PR acumuladas que tienes y un cambio aquí puede generar conflictos. Hay que solucionarlo tan pronto como se pueda.

2022-12-22 14:41 UTC, josem-perram commented on app/src/main/res/values/strings.xml
> +    <string name="save_button_text">GUARDAR RSS</string>
Quizás la segunda palabra del GUARDAR RSS sobra porque ya se sobreentiende que estamos guardando un RSS.

2022-12-30 11:41 UTC, albertoag128 commented on app/src/main/java/com/example/rssapp/management/presentation/RssBottomSheetFragment.kt
> +                viewModel?.saveRss(
Vale perfecto, será cambiado cuanto antes

2022-12-30 11:42 UTC, albertoag128 commented on app/src/main/res/values/strings.xml
> +    <string name="save_button_text">GUARDAR RSS</string>
De acuerdo, dejaré solo "GUARDAR"

2022-12-30 11:43 UTC, merged