Domain save RSS use case done
albertoag128/RssAndroidApp pull request #3
Opened 2022-11-16 08:27 UTC by albertoag128

## Descripción de la tarea
En esta tarea se va a implementar la manera de guardar RSS en nuestra aplicación.

## Como ha sido implementado
Mi planteamiento es el siguiente: he creado el repositorio de dominio de momento solo atentiendo a la funcion de guardar un RSS (ya en el futuro podremos añadir como borrar un RSS y otras funcionalidades). Tambien he decidido sacar el modelo de datos fuera del caso de uso, dado que va a haber varios casos de uso que lo utilicen y por tanto no tendría sentido que estuviera dentro de dichos casos. Por último tenemos el caso de uso que mediante un execute, y el paso de los parámetros name y url, construye un objeto y lo guarda.

## Palabras clave
Dominio, Caso de uso, Interfaz, Repositorio, Modelo

2022-11-16 14:43 UTC, MiM14 approved these changes
👌

2022-11-16 15:16 UTC, josem-perram requested changes
Please, revisa los comentarios, son sobre todo de namings. Yo veo como dos tipos de RSS, uno los propios RSS que se obtienen de las distintas páginas web y otro los que gestiona el usuario. Realmente el usuario introduce información "personal" (name) de un RSS pero realmente no son RSS, de ahí que quizás UserRss**** podría ser un buen naming. Esto es mi opinión, puedes tirar con tu concepto, cuando avancemos con la aplicación quizás vaya quedando más claro y cambiar los nombres es algo sencillo.

2022-11-16 15:16 UTC, josem-perram commented on app/src/main/java/com/example/rssapp/management/domain/ManagementAddRssUseCase.kt
> +class ManagementAddRssUseCase(val repository: ManagementRepository) {
Sugerencia de naming para el caso de uso: AddRssUseCase

2022-11-16 15:16 UTC, josem-perram commented on app/src/main/java/com/example/rssapp/management/domain/ManagementModel.kt
> +data class ManagementModel(val name:String, val url:String)
UserRssModel ?? Lo de user viene porque son RSS asociados al usuario.

2022-11-16 15:16 UTC, josem-perram commented on app/src/main/java/com/example/rssapp/management/domain/ManagementRepository.kt
> +interface ManagementRepository {
Sugerencia naming: UserRssRepository la idea de este repositorio es gestionar los RSS introducidos por el usuario: crear, eliminar, obtener....

2022-11-16 17:25 UTC, MiM14 approved these changes
La pr esta 👍

2022-11-17 08:11 UTC, josem-perram approved these changes
Genial!

2022-11-17 15:07 UTC, merged