Navegación entre pantallas con menú principal hecho
albertoag128/RssAndroidApp pull request #7
Opened 2022-11-17 15:44 UTC by albertoag128

## DESCRIPCION
Esta pull request está enfocada a desarrollar un menu en la parte de abajo de la vista que nos permita cambiar entre fragmentos.

## COMO HA SIDO IMPLEMENTADO
Hemos creado un grafo de navegacion en el cual indicaremos los distintos fragmentos a los que queremos navega.
La vista de activity_main contendra un fragment container donde se carguen nuestros fragmentos y ademas un menu en la parte de abajo de la vista.
Crearemos varios fragmentos para las distintas funcionalidades de nuestra aplicacion y en la actividad principal declararemos un set on click listener que evaluara que item se esta seleccionando para navegar hasta el.

## DISCLAIMER
Por el momento no hemos añadido navegación segura, pero es algo que se hará cuando el proyecto esté más avanzado.

## PALABRAS CLAVE
UI, navigation, graph, destination, presentation

## SCREENSHOTS OR VIDEO

https://user-images.githubusercontent.com/91797204/202491414-2431f334-9f37-46f5-a5e5-d0c7a949a4f4.mp4

2022-11-17 17:27 UTC, OscarAntona approved these changes
Lo veo todo correcto🔥🔥

2022-11-21 11:39 UTC, josem-perram requested changes
Hola! @albertoag128 please, añade la navegación segura para dar por concluido el ticket pues es un requisito del mismo y no hacerlo estaríamos dando una visión errónea del mismo. Yo te ayudo a añadirlo. Gracias.
@OscarAntona como revisores, tenemos que ayudar al autor dándole feedback de todo, este descuido puede traer consecuencia de exceso de trabajo a medio plazo. Gracias.

2022-11-21 12:06 UTC, albertoag128 commented
vale perfecto, pues esta tarde lo podemos mirar en clase para ver como añadirlo de forma correcta y dar por concluido el ticket

2022-11-21 13:13 UTC, OscarAntona commented
Tienes razon chema, no me fije en eso la verdad.

2022-11-21 18:50 UTC, albertoag128 commented
Hola, ya he actualizado todo y he añadido navegación segura a la aplicación. Además de ello, he probado varias veces la app y funciona, asi que en principio, eso sería todo para este ticket.

2022-11-22 14:28 UTC, OscarAntona approved these changes
Veo que ya has añadido Safe navigation, asi que con eso y todo lo anterior ya se cumplen todos los objetivos del ticket 👍

2022-11-22 15:24 UTC, merged